name: Build Minecraft Plugin

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: mvn clean package
      - uses: actions/upload-artifact@v4
        with:
          name: Plugin-JAR
          path: target/*.jar

